#!/usr/bin/env bash
# This script installs nginx and configures it to return custom headers

apt-get update
apt-get -y install nginx
service nginx start

# Initialize variables
cfg_file='/etc/nginx/sites-enabled/default'
header_line="    add_header X-Served-By \$hostname;"

# Configure index page
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Update server to listen on default port 80
sed -r -i 's|^(\tlisten [^0-9]*)[0-9]+|\180|' $cfg_file

# Add the header line to the configuration file
sed -i "/^\s*location\s*\/\s*{/a $header_line" $cfg_file

service nginx reload

