#!/usr/bin/env bash
#  configure it to our needs so that you can connect to a server without typing a password

Host 'web-01'
	HostName 34.227.91.195
	User ubuntu
	PubkeyAuthentication yes
	IdentityFile ~/.ssh/school
	PasswordAuthentication no
